# Generated by Django 4.0.3 on 2022-03-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='History', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blogtest.course'),
        ),
    ]
