# Generated by Django 4.0.3 on 2022-04-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogtest', '0007_alter_submission_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_on',
            new_name='post',
        ),
    ]
