# Generated by Django 4.0.3 on 2022-04-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogtest', '0009_comment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pub_date',)},
        ),
    ]
