# Generated by Django 4.0.3 on 2022-04-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogtest', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='url',
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
