# Generated by Django 4.0.3 on 2022-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogtest', '0011_remove_submission_url_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
